require 'euler'

# Problem 44
# 23 May 2003
# Pentagonal numbers are generated by the formula, Pn=n(3n1)/2. The first ten pentagonal numbers are:
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference is pentagonal and D = |Pk - Pj| is minimised; what is the value of D?

P = (1..20000).collect{|n|n*(3*n-1)/2}

class Numeric
  def pentagonal?
    return false if self < 1
    ((1+24*self)**0.5+1) % 6 == 0
  end
end

P.all?(&:pentagonal?).should == true
P.collect{|n|n+1}.any?(&:pentagonal?).should == false

def P.iterate
  (0...P.size).each do |n|
    n.downto(0) do |m|
      yield n,m
    end
  end
end


n,m = P.enum_for(:iterate).detect do |n,m|
  a,b = P[n],P[m]
  (a+b).pentagonal? && (a-b).pentagonal?
end

(P[n]-P[m]).should == 5482660